### PR TITLE
Remove Old History, Old Swap, All Rx Library!!!! - After removing FT

### PR DESCRIPTION
**Pull request by bigearsenal**
## Description of the changes
- Wait after FT "keyapp_swap_jupiter_enabled" and "history_service_enabled" are allowed to be removed

### CODE REVIEW

**Review by qwerkly — APPROVED** [review]

**Review by TrGiLong — APPROVED** [review]

**Comment by sidorov-panda** [comment]
Needs to remove "jupiterSwapEnabled" FT from the list, since it has no use anymore

**Comment by sidorov-panda** [comment]
Remove New folder from: "WalletDetail/New" -> "WalletDetail/"

**Comment by bigearsenal** [comment]
> Needs to remove "jupiterSwapEnabled" FT from the list, since it has no use anymore

It has already been removed. Or did you mean "remove from firebase"?

**Comment by bigearsenal** [comment]
> Remove "New" folder from: "WalletDetail/New" -> "WalletDetail/"

Thanks. But at the moment I will only remove file, the file structure will be keep unchanged to prevent it from conflict with `wormhole`

**Pull request merged**
