### PR TITLE
Refactor/update textfield from swap view model

### PR DESCRIPTION
**Pull request by bigearsenal**
## Problems
- After switching fromToken and toToken, the `amountTo` become the `amountFrom` and the TextField's value must reflect this change accordingly.
- Temporary solution is using and object in `JupiterSwapBusinessLogic` to perform the `forceUpdateAmountFrom` changes and make `SwapInputViewModel` listen to it. But the `JupiterSwapBusinessLogic` must not be responsible for it, the `SwapViewModel` needs to handle this case. 
- There was no logic to handle any input from `SwapViewModel`.
## Solution
- Add `SwapInputViewModel` instances to `SwapViewModel` to handle potential input behavior in `SwapViewModel`.
- Modify fromAmount when switching fromToken and toToken in `SwapViewModel` after the action.
- Remove the `forceUpdateAmountFrom` logic from `JupiterSwapBusinessLogic`.

### CODE REVIEW

**Comment by lisemyon** [comment]
I don't mind using this solution right now but I guess it could be also possible to pass "switch" changes via JupiterSwapCoordinator to internal input viewModels via PassthroughSubjects

**Review by lisemyon — APPROVED** [review]

**Comment by bigearsenal** [comment]
> I don't mind using this solution right now but I guess it could be also possible to pass "switch" changes via JupiterSwapCoordinator to internal input viewModels via PassthroughSubjects

I think Coordinator is also responsible for routing, not modifying anything. Or did I get you wrong?

**Comment by lisemyon** [comment]
You got it right. @qwerkly might help me on that. As far as I understood, viewModel should not know about other viewModels as it will break single responsibility rule. In this case the coordinator is the one who links these 3 objects.

**Comment by bigearsenal** [comment]
@lisemyon let discuss this later, i'm merging it for now

**Pull request merged**
