### PR TITLE
[PWN-7497] Dismiss swap screen if it is opened via action panel

### PR DESCRIPTION
**Pull request by lisemyon**
## Link jira to issue
https://p2pvalidator.atlassian.net/browse/PWN-7497

## Description of the changes
-

### CODE REVIEW

**Review by bigearsenal — CHANGES_REQUESTED** [review]
Need to also redirect user to home in all Swap scene

**Comment by lisemyon** [comment]
> Need to also redirect user to home in all Swap scene

even if it is tapped via tab bar ?

**Comment by bigearsenal** [comment]
> https://p2pvalidator.atlassian.net/browse/PWN-7497

I don't quite sure, can you check the documentation?

**Comment by lisemyon** [comment]
> > https://p2pvalidator.atlassian.net/browse/PWN-7497
> 
> I don't quite sure, can you check the documentation or ask the product team?

yes you are right, we need to redirect from one tab to another. I have not known. will fix it

**Review by bigearsenal — APPROVED** [review]

**Pull request merged**
